# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
     firewalls:
         secured_area:
             pattern:    ^/
             anonymous: ~
             http_basic:
                 realm: "Secured Area"

     access_control:
         - { path: ^/, roles: ROLE_ADMIN }

     providers:
         in_memory:
             memory:
                 users:
                     admin: { password: nuf0d, roles: 'ROLE_ADMIN' }

     encoders:
         Symfony\Component\Security\Core\User\User: plaintext