AppBundle\Entity\Playlist:
    type: entity
    table: playlist
    uniqueConstraints:
        playlistId:
            columns:
                - playlistId
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        playlistid:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: playlistId
        playlisttitle:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: playlistTitle
        playlistdescription:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: playlistDescription
    lifecycleCallbacks: {  }
